namespace Windows.Foundation
{
    /// <summary>
    /// Represents a method that handles general events.
    /// </summary>
    /// <typeparam name="TSender">The object type.</typeparam>
    /// <typeparam name="TResult">The type of event data generated by the event.</typeparam>
    /// <param name="sender"></param>
    /// <param name="args"></param>
    public delegate void TypedEventHandler<TSender, TResult>(TSender sender, TResult args);
}